### ISSUE TITLE
 1 : Design Onboarding Pages for the Chat App. [Max 3]

### ISSUE THREAD

**Issue by tktakshila** [GeekHaven/design-for-chat-app#1]
Design Onboarding Pages for the Chat App.
Select a theme and you need to stick to it for the entire project.
So, choose your theme wisely.
Maximum 3 Onboarding Pages.
Submit the Figma link and jpeg/png files of the designs in the onboarding screen folder.

**Comment by mysterio0801** [comment]
I want to work on this.

**Comment by tktakshila** [comment]
> I want to work on this.

Go on

**Comment by sneha1010** [comment]
can i contribute

**Comment by tktakshila** [comment]
> can i contribute

Ok, do it before today midnight.

**Comment by zorione** [comment]
I want to work on this @tktakshila

**Comment by tktakshila** [comment]
> I want to work on this @tktakshila

Sure, go on.

**Comment by Kgupta20** [comment]
can i work on this?

**Comment by AsheX9** [comment]
Can I contribute?

**Comment by tktakshila** [comment]
> can i work on this?

Yes..

**Comment by tktakshila** [comment]
> Can I contribute?

Sure, bro
