### ISSUE TITLE
3: Design Icons for the chat app and submit them in SVG format [ Read Description ].

### ISSUE THREAD

**Issue by tktakshila** [GeekHaven/design-for-chat-app#14]
Design icons for :
-My Profile
-Chat List
-Find Friends
Submit your icons in SVG format in the Icons folder.

**Comment by sneha1010** [comment]
can i work on this?

**Comment by tktakshila** [comment]
> can i work on this?

sure

**Comment by AshexX** [comment]
Can i contribute?

**Comment by khu-shhii** [comment]
can i work on this?

**Comment by tktakshila** [comment]
> Can i contribute?

sure

**Comment by tktakshila** [comment]
> can i work on this?

sure
