### ISSUE TITLE
2: Design a logo for the Chat App.

### ISSUE THREAD

**Issue by tktakshila** [GeekHaven/design-for-chat-app#2]
Design a logo for the chat app and submit it in png/svg format in the Logo folder.

**Comment by geeks5551** [comment]
hey can i contribute to this issue @tktakshila

**Comment by Smitesh25** [comment]
I want to work on this @tktakshila

**Comment by tktakshila** [comment]
> I want to work on this @tktakshila

Sure, bro

**Comment by CodeDropper** [comment]
I want to submit a logo design, @tktakshila

**Comment by tktakshila** [comment]
> I want to submit a logo design, @tktakshila

Sure

**Comment by Tushargupta9800** [comment]
Can I contribute here?? @tktakshila

**Comment by tktakshila** [comment]
> Can I contribute here?? @tktakshila

Sure, you have got two days.

**Comment by sneha1010** [comment]
can I contribute in this?

**Comment by tktakshila** [comment]
> can I contribute in this?

ok, submit your PR today before midnight.

**Comment by sneha1010** [comment]
@tktakshila please review my logo

**Comment by zorione** [comment]
Can I submit the logo @tktakshila

**Comment by tktakshila** [comment]
> Can I submit the logo @tktakshila

Yes, sure

**Comment by tktakshila** [comment]
> @tktakshila please review my logo

Nice

**Comment by AsheX9** [comment]
Can I contribute?

**Comment by Kgupta20** [comment]
can i work on this?

**Comment by tktakshila** [comment]
> Can I contribute?

Yes bro, go ahead.

**Comment by tktakshila** [comment]
> can i work on this?

Go Ahead.
